Importing Libraries :

In [2]:
import pandas as pd
import numpy as np

Importing iris dataset from sklearn.dataset

  * Here the sklearn is the popular framework for macmachine learning.
  * we are loading iris dataset by using load_iris().

In [4]:
from sklearn.datasets import load_iris
iris_dataset = load_iris()

To know the form of iris dataset we are displaying its key:


In [6]:
print("Keys of iris dataset : {}".format(iris_dataset.keys()))

Keys of iris dataset : dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])


Displays the values stored in 'DESCR' key :

In [7]:
print(iris_dataset['DESCR'][:200]+"\n ...")

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive
 ...


Displays the values store in 'target_names' key :

In [8]:
print("Target Names : {}".format(iris_dataset['target_names']))

Target Names : ['setosa' 'versicolor' 'virginica']


Displays values stored in the 'feature_names' key :

In [10]:
print("Feature Names : {}".format(iris_dataset['feature_names']))

Feature Names : ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


Displays the type of the 'data' key :

In [11]:
print("Type of data : {} ".format(type(iris_dataset['data'])))

Type of data : <class 'numpy.ndarray'> 


Displays the shape of data :

In [16]:
print("Shape of data : {}".format(iris_dataset['data'].shape))

Shape of data : (150, 4)


This line of code prints the first five rows of data-key :

In [14]:
print("First five rows of data : \n{}".format(iris_dataset['data'][:5]))

First five rows of data : 
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


This line of code prints the type of 'target' key :

In [17]:
print("Type of target : {}".format(type(iris_dataset['target'])))

Type of target : <class 'numpy.ndarray'>


Displays the shape of 'target' key  :

In [18]:
print("Shape of target : {}".format(iris_dataset['target'].shape))

Shape of target : (150,)


To display the values stored in 'target' key :

In [19]:
print("Target :\n {}".format(iris_dataset['target']))

Target :
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


To train and test the iris-data we are using sklearn.model_selection

  * Here we are importing train_test_split from sklearn.model_selection


In [25]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split( 
                                   iris_dataset['data'],iris_dataset['target'],random_state=0 )

Shape of nd arrays (x_train, y_train, x_test, y_test) after splitting :

In [26]:
print("Shape of X_train : {}".format(X_train.shape))
print("Shape of y_train : {}".format(y_train.shape))
print("Shape of X_test : {}".format(X_test.shape))
print("Shape of y_test : {}".format(y_test.shape))

Shape of X_train : (112, 4)
Shape of y_train : (112,)
Shape of X_test : (38, 4)
Shape of y_test : (38,)


Now we are importing KNeighborsClassifier from sklearn.neighneighbors 

  * Also, we assign k-nearest neighneighbors equal to 1 by using     KNeighborsClassifier function to knn. 




In [23]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=1)

We trained the model in training data :

In [27]:
knn.fit(X_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=1, p=2,
                     weights='uniform')

Creating numpy array named X_new and printing the shape of it :

In [30]:
X_new = np.array([[5,2.9,1,0.2]])
print("X_new shape : {}".format(X_new.shape))

X_new shape : (1, 4)


Making predictions with the help of predict method of knn object :

In [31]:
prediction = knn.predict(X_new)
print("Prediction : {}".format(prediction))
print("Predicted target name : {}".format(iris_dataset['target_names'][prediction]))

Prediction : [0]
Predicted target name : ['setosa']


Evaluating the model by testing it on test dataset :

In [33]:
y_pred=knn.predict(X_test)
print("Test set predictions : \n{}".format(y_pred))

Test set predictions : 
[2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0 2 1 0 2 2 1 0
 2]


Displaying test score :

In [36]:
print("Test set score : {}".format(np.mean(y_pred == y_test)))

Test set score : 0.9736842105263158
